EXAMPLE_VENUES = [{'id': 'hotel', 'label': 'ホテル'},
 {'id': 'museum', 'label': '美術館'},
 {'id': 'fast_food', 'label': 'ファストフード店'},
 {'id': 'apparel', 'label': 'アパレル'}]

# 接客例の初期会話。base_text はデフォルト表示で使う店員発話。
# intent_parts は、発話の一部にどの発話意図の声色・表情・お辞儀を適用するかの目印。
EXAMPLE_SCENES = [{'id': 'hotel_checkin',
  'venue': 'hotel',
  'title': '手続き系: チェックイン',
  'turns': [{'role': 'customer', 'text': 'すみません、今日から一泊で予約している田中です。'},
            {'role': 'staff',
             'base_text': '田中様でいらっしゃいますね。本日はご宿泊いただき、誠にありがとうございます。ご本人様確認のため、身分証明書を拝見してもよろしいでしょうか？',
             'intent_parts': [{'intent': 'question', 'text': '田中様でいらっしゃいますね。'},
                              {'intent': 'gratitude', 'text': '本日はご宿泊いただき、誠にありがとうございます。'},
                              {'intent': 'request', 'text': 'ご本人様確認のため、身分証明書を拝見してもよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'はい、これです。'},
            {'role': 'staff',
             'base_text': '誠にありがとうございます。確認が取れました。朝食付きのプランにて承っております。お支払いは現金でよろしいでしょうか？',
             'intent_parts': [{'intent': 'gratitude', 'text': '誠にありがとうございます。'},
                              {'intent': 'explanation', 'text': '確認が取れました。朝食付きのプランにて承っております。'},
                              {'intent': 'question', 'text': 'お支払いは現金でよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'はい、現金でお願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。それではお手続きを進めてまいりますので、少々お待ちいただけますでしょうか？',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'request', 'text': 'それではお手続きを進めてまいりますので、少々お待ちいただけますでしょうか？'}]}]},
 {'id': 'hotel_dirty_bed',
  'venue': 'hotel',
  'title': '謝罪系: ベッドが汚れていた',
  'turns': [{'role': 'customer', 'text': '部屋に入ったら、ベッドが少し汚れていたんですけど。'},
            {'role': 'staff',
             'base_text': '誠に申し訳ございません。ご到着早々にご不快な思いをおかけしました。直ちに状況を確認し、代わりのお部屋をご用意できるか確認いたします。',
             'intent_parts': [{'intent': 'apology', 'text': '誠に申し訳ございません。'},
                              {'intent': 'apology', 'text': 'ご到着早々にご不快な思いをおかけしました。'},
                              {'intent': 'apology', 'text': '直ちに状況を確認し、代わりのお部屋をご用意できるか確認いたします。'}]},
            {'role': 'customer', 'text': 'できれば部屋を変えてほしいです。'},
            {'role': 'staff',
             'base_text': 'もちろんでございます。お荷物のご移動もこちらでお手伝いいたしますので、少々お時間をいただいてもよろしいでしょうか？',
             'intent_parts': [{'intent': 'acceptance', 'text': 'もちろんでございます。'},
                              {'intent': 'request', 'text': 'お荷物のご移動もこちらでお手伝いいたしますので、少々お時間をいただいてもよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'お願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。直ちに対応いたします。このたびは誠に申し訳ございません。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'explanation', 'text': '直ちに対応いたします。'},
                              {'intent': 'apology', 'text': 'このたびは誠に申し訳ございません。'}]}]},
 {'id': 'hotel_checkout',
  'venue': 'hotel',
  'title': '感謝系: チェックアウト',
  'turns': [{'role': 'customer', 'text': 'チェックアウトお願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。ご宿泊いただき誠にありがとうございました。お部屋番号をお伺いしてもよろしいでしょうか？',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'gratitude', 'text': 'ご宿泊いただき誠にありがとうございました。'},
                              {'intent': 'request', 'text': 'お部屋番号をお伺いしてもよろしいでしょうか？'}]},
            {'role': 'customer', 'text': '305号室です。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。追加のご利用はございませんので、こちらでチェックアウトのお手続きは完了でございます。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'explanation', 'text': '追加のご利用はございませんので、こちらでチェックアウトのお手続きは完了でございます。'}]},
            {'role': 'customer', 'text': 'ありがとうございました。'},
            {'role': 'staff',
             'base_text': 'こちらこそ誠にありがとうございました。またお近くへお越しの際は、ぜひご利用くださいませ。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'こちらこそ誠にありがとうございました。'},
                              {'intent': 'request', 'text': 'またお近くへお越しの際は、ぜひご利用くださいませ。'}]}]},
 {'id': 'hotel_sightseeing',
  'venue': 'hotel',
  'title': '質問系: 近くの観光スポット',
  'turns': [{'role': 'customer', 'text': 'この近くで少し観光できる場所ってありますか？'},
            {'role': 'staff',
             'base_text': 'はい、徒歩圏内でしたら、川沿いの散策コースと歴史資料館が人気でございます。お時間が短い場合は、川沿いの方がご利用しやすいかと存じます。',
             'intent_parts': [{'intent': 'explanation', 'text': 'はい、徒歩圏内でしたら、川沿いの散策コースと歴史資料館が人気でございます。'},
                              {'intent': 'explanation', 'text': 'お時間が短い場合は、川沿いの方がご利用しやすいかと存じます。'}]},
            {'role': 'customer', 'text': '1時間くらいしかないんですけど、行けますか？'},
            {'role': 'staff',
             'base_text': 'それでしたら川沿いがおすすめでございます。ホテルから徒歩10分ほどですので、お戻りの時間も含めてちょうどよいかと存じます。',
             'intent_parts': [{'intent': 'explanation', 'text': 'それでしたら川沿いがおすすめでございます。'},
                              {'intent': 'explanation', 'text': 'ホテルから徒歩10分ほどですので、お戻りの時間も含めてちょうどよいかと存じます。'}]},
            {'role': 'customer', 'text': 'いいですね。行ってみます。'},
            {'role': 'staff',
             'base_text': 'ぜひお楽しみください。フロントにて簡単な地図もお渡しできますので、よろしければお持ちくださいませ。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ぜひお楽しみください。'},
                              {'intent': 'request', 'text': 'フロントにて簡単な地図もお渡しできますので、よろしければお持ちくださいませ。'}]}]},
 {'id': 'museum_ticket',
  'venue': 'museum',
  'title': '手続き系: チケット購入',
  'turns': [{'role': 'customer', 'text': '大人1枚お願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。一般の当日券を1枚でございますね。常設展と特別展の両方をご覧になりますでしょうか？',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'explanation', 'text': '一般の当日券を1枚でございますね。'},
                              {'intent': 'question', 'text': '常設展と特別展の両方をご覧になりますでしょうか？'}]},
            {'role': 'customer', 'text': '特別展だけで大丈夫です。'},
            {'role': 'staff',
             'base_text': '承知いたしました。特別展のみでしたら、こちらのチケットでございます。館内は再入場できませんので、ご注意くださいませ。',
             'intent_parts': [{'intent': 'acceptance', 'text': '承知いたしました。'},
                              {'intent': 'explanation', 'text': '特別展のみでしたら、こちらのチケットでございます。'},
                              {'intent': 'request', 'text': '館内は再入場できませんので、ご注意くださいませ。'}]},
            {'role': 'customer', 'text': 'わかりました。'},
            {'role': 'staff',
             'base_text': '誠にありがとうございます。入口は右手奥でございます。どうぞごゆっくりご鑑賞くださいませ。',
             'intent_parts': [{'intent': 'gratitude', 'text': '誠にありがとうございます。'},
                              {'intent': 'explanation', 'text': '入口は右手奥でございます。'},
                              {'intent': 'request', 'text': 'どうぞごゆっくりご鑑賞くださいませ。'}]}]},
 {'id': 'museum_highlight',
  'venue': 'museum',
  'title': '質問系: おすすめの見どころ',
  'turns': [{'role': 'customer', 'text': '初めて来たんですけど、どこから見るのがおすすめですか？'},
            {'role': 'staff',
             'base_text': '初めてでしたら、まず2階の特別展示からご覧いただくのがおすすめでございます。代表作がまとまっており、全体の雰囲気をつかみやすくなっております。',
             'intent_parts': [{'intent': 'explanation', 'text': '初めてでしたら、まず2階の特別展示からご覧いただくのがおすすめでございます。'},
                              {'intent': 'explanation', 'text': '代表作がまとまっており、全体の雰囲気をつかみやすくなっております。'}]},
            {'role': 'customer', 'text': 'どれくらい時間がかかりますか？'},
            {'role': 'staff',
             'base_text': 'ゆっくりご覧になる場合は1時間ほどでございます。短めでしたら、入口近くの3作品を中心にご覧いただくと楽しみやすいかと存じます。',
             'intent_parts': [{'intent': 'explanation', 'text': 'ゆっくりご覧になる場合は1時間ほどでございます。'},
                              {'intent': 'explanation', 'text': '短めでしたら、入口近くの3作品を中心にご覧いただくと楽しみやすいかと存じます。'}]},
            {'role': 'customer', 'text': 'じゃあ特別展示から見ます。'},
            {'role': 'staff',
             'base_text': 'はい。階段を上がって正面が入口でございます。作品解説のリーフレットもございますので、ぜひお持ちくださいませ。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'はい。'},
                              {'intent': 'explanation', 'text': '階段を上がって正面が入口でございます。'},
                              {'intent': 'request', 'text': '作品解説のリーフレットもございますので、ぜひお持ちくださいませ。'}]}]},
 {'id': 'museum_distance_warning',
  'venue': 'museum',
  'title': '注意系: 展示物に近づきすぎた',
  'turns': [{'role': 'customer', 'text': 'これ、かなり近くで見てもいいですか？'},
            {'role': 'staff',
             'base_text': '恐れ入ります。作品保護のため、柵の内側には入らず、こちらの位置からご覧いただけますでしょうか？',
             'intent_parts': [{'intent': 'apology', 'text': '恐れ入ります。'},
                              {'intent': 'explanation', 'text': '作品保護のため、柵の内側には入らず、'},
                              {'intent': 'request', 'text': 'こちらの位置からご覧いただけますでしょうか？'}]},
            {'role': 'customer', 'text': 'あ、すみません。'},
            {'role': 'staff',
             'base_text': 'ご協力ありがとうございます。細部をご覧になりたい場合は、横に拡大写真のパネルもございます。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ご協力ありがとうございます。'},
                              {'intent': 'explanation', 'text': '細部をご覧になりたい場合は、横に拡大写真のパネルもございます。'}]},
            {'role': 'customer', 'text': 'そうなんですね。'},
            {'role': 'staff',
             'base_text': 'はい。そちらでしたら筆の跡まで見やすくなっておりますので、ぜひご覧くださいませ。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'はい。'},
                              {'intent': 'explanation', 'text': 'そちらでしたら筆の跡まで見やすくなっておりますので、'},
                              {'intent': 'request', 'text': 'ぜひご覧くださいませ。'}]}]},
 {'id': 'museum_lost_companion',
  'venue': 'museum',
  'title': '困りごと系: 同行者とはぐれた',
  'turns': [{'role': 'customer', 'text': 'すみません、一緒に来た人とはぐれてしまって。'},
            {'role': 'staff',
             'base_text': 'それはご心配でございますね。館内放送は原則行っておりませんが、受付付近でお待ちいただくか、スタッフ間で見かけた際にお声がけすることは可能でございます。',
             'intent_parts': [{'intent': 'apology', 'text': 'それはご心配でございますね。'},
                              {'intent': 'explanation',
                               'text': '館内放送は原則行っておりませんが、受付付近でお待ちいただくか、スタッフ間で見かけた際にお声がけすることは可能でございます。'}]},
            {'role': 'customer', 'text': '受付で待っていた方がいいですかね。'},
            {'role': 'staff',
             'base_text': 'はい、その方が合流しやすいかと存じます。お相手の方の特徴を簡単に伺ってもよろしいでしょうか？',
             'intent_parts': [{'intent': 'explanation', 'text': 'はい、その方が合流しやすいかと存じます。'},
                              {'intent': 'request', 'text': 'お相手の方の特徴を簡単に伺ってもよろしいでしょうか？'}]},
            {'role': 'customer', 'text': '黒いコートを着ています。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。近くのスタッフにも共有いたしますので、受付付近でお待ちくださいませ。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'explanation', 'text': '近くのスタッフにも共有いたしますので、'},
                              {'intent': 'request', 'text': '受付付近でお待ちくださいませ。'}]}]},
 {'id': 'fast_food_order',
  'venue': 'fast_food',
  'title': '手続き系: 注文',
  'turns': [{'role': 'customer', 'text': 'チーズバーガーセットをください。'},
            {'role': 'staff',
             'base_text': 'チーズバーガーセットでございますね。サイドはポテトでよろしいでしょうか？',
             'intent_parts': [{'intent': 'question', 'text': 'チーズバーガーセットでございますね。サイドはポテトでよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'はい、ポテトで。'},
            {'role': 'staff',
             'base_text': 'ドリンクはいかがなさいますでしょうか？',
             'intent_parts': [{'intent': 'question', 'text': 'ドリンクはいかがなさいますでしょうか？'}]},
            {'role': 'customer', 'text': 'コーラでお願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。チーズバーガーセット、ポテト、コーラでお会計は780円でございます。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'explanation', 'text': 'チーズバーガーセット、ポテト、コーラでお会計は780円でございます。'}]}]},
 {'id': 'fast_food_recommendation',
  'venue': 'fast_food',
  'title': '質問系: おすすめを聞く',
  'turns': [{'role': 'customer', 'text': '初めて来たんですけど、おすすめありますか？'},
            {'role': 'staff',
             'base_text': 'でしたら、定番はチーズバーガーセットでございます。しっかり召し上がりたい方にはダブルバーガーも人気です。',
             'intent_parts': [{'intent': 'explanation',
                               'text': 'でしたら、定番はチーズバーガーセットでございます。しっかり召し上がりたい方にはダブルバーガーも人気です。'}]},
            {'role': 'customer', 'text': '軽めがいいです。'},
            {'role': 'staff',
             'base_text': 'それでしたら、チーズバーガーセットか、単品に小さめのサイドをお付けするのがおすすめです。',
             'intent_parts': [{'intent': 'explanation', 'text': 'それでしたら、チーズバーガーセットか、単品に小さめのサイドをお付けするのがおすすめです。'}]},
            {'role': 'customer', 'text': 'じゃあチーズバーガーセットで。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。ドリンクは何になさいますでしょうか？',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'question', 'text': 'ドリンクは何になさいますでしょうか？'}]}]},
 {'id': 'fast_food_wrong_drink',
  'venue': 'fast_food',
  'title': '謝罪系: 注文と違う商品が出た',
  'turns': [{'role': 'customer', 'text': 'すみません、コーラを頼んだんですけど、これウーロン茶になってます。'},
            {'role': 'staff',
             'base_text': '誠に申し訳ございません。すぐにコーラと交換いたします。レシートを確認させていただいてもよろしいでしょうか？',
             'intent_parts': [{'intent': 'apology', 'text': '誠に申し訳ございません。'},
                              {'intent': 'explanation', 'text': 'すぐにコーラと交換いたします。'},
                              {'intent': 'request', 'text': 'レシートを確認させていただいてもよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'はい。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。こちらの確認不足でございました。すぐにお持ちいたしますので、少々お待ちくださいませ。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'apology', 'text': 'こちらの確認不足でございました。'},
                              {'intent': 'request', 'text': 'すぐにお持ちいたしますので、少々お待ちくださいませ。'}]},
            {'role': 'customer', 'text': 'お願いします。'},
            {'role': 'staff',
             'base_text': 'お待たせしてしまい誠に申し訳ございません。こちらがコーラでございます。',
             'intent_parts': [{'intent': 'apology', 'text': 'お待たせしてしまい誠に申し訳ございません。'},
                              {'intent': 'explanation', 'text': 'こちらがコーラでございます。'}]}]},
 {'id': 'fast_food_hurry',
  'venue': 'fast_food',
  'title': '急ぎ系: 時間がない客',
  'turns': [{'role': 'customer', 'text': 'すみません、すぐ出られるものってありますか？'},
            {'role': 'staff',
             'base_text': 'はい、ただいまでしたらチキンバーガーとポテトはすぐにご用意できます。セットでも単品でも承れます。',
             'intent_parts': [{'intent': 'explanation', 'text': 'はい、ただいまでしたらチキンバーガーとポテトはすぐにご用意できます。'},
                              {'intent': 'explanation', 'text': 'セットでも単品でも承れます。'}]},
            {'role': 'customer', 'text': 'じゃあチキンバーガー単品で。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。お会計は420円でございます。すぐにお渡しいたします。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'explanation', 'text': 'お会計は420円でございます。すぐにお渡しいたします。'}]},
            {'role': 'customer', 'text': 'ありがとうございます。'},
            {'role': 'staff',
             'base_text': 'お待たせいたしました。こちらチキンバーガーでございます。お気をつけてお持ちくださいませ。',
             'intent_parts': [{'intent': 'explanation', 'text': 'お待たせいたしました。こちらチキンバーガーでございます。'},
                              {'intent': 'request', 'text': 'お気をつけてお持ちくださいませ。'}]}]},
 {'id': 'apparel_size',
  'venue': 'apparel',
  'title': '質問系: サイズを聞く',
  'turns': [{'role': 'customer', 'text': 'この服、Mサイズってありますか？'},
            {'role': 'staff',
             'base_text': '確認いたします。こちらのお色でしたら、Mサイズは店頭に1点ございます。',
             'intent_parts': [{'intent': 'acceptance', 'text': '確認いたします。'},
                              {'intent': 'explanation', 'text': 'こちらのお色でしたら、Mサイズは店頭に1点ございます。'}]},
            {'role': 'customer', 'text': '試着できますか？'},
            {'role': 'staff',
             'base_text': 'もちろんでございます。試着室は奥にございますので、ご案内いたします。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'もちろんでございます。'},
                              {'intent': 'explanation', 'text': '試着室は奥にございますので、ご案内いたします。'}]},
            {'role': 'customer', 'text': 'ありがとうございます。'},
            {'role': 'staff',
             'base_text': 'ご試着後にサイズ感が気になりましたら、SやLもお持ちできますので、お声がけくださいませ。',
             'intent_parts': [{'intent': 'explanation', 'text': 'ご試着後にサイズ感が気になりましたら、SやLもお持ちできますので、'},
                              {'intent': 'request', 'text': 'お声がけくださいませ。'}]}]},
 {'id': 'apparel_coordination',
  'venue': 'apparel',
  'title': '提案系: 似合う服を相談',
  'turns': [{'role': 'customer', 'text': 'こういう服あまり着ないんですけど、似合いますかね。'},
            {'role': 'staff',
             'base_text': 'お似合いになるかと存じます。普段のお洋服に合わせる場合は、少し落ち着いたお色の方が取り入れやすいかもしれません。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'お似合いになるかと存じます。'},
                              {'intent': 'explanation', 'text': '普段のお洋服に合わせる場合は、少し落ち着いたお色の方が取り入れやすいかもしれません。'}]},
            {'role': 'customer', 'text': '派手すぎるのはちょっと不安です。'},
            {'role': 'staff',
             'base_text': 'でしたら、こちらのネイビーはいかがでしょうか？形は同じですが、印象が少し落ち着いて見えます。',
             'intent_parts': [{'intent': 'question', 'text': 'でしたら、こちらのネイビーはいかがでしょうか？'},
                              {'intent': 'explanation', 'text': '形は同じですが、印象が少し落ち着いて見えます。'}]},
            {'role': 'customer', 'text': 'それなら着やすそうです。'},
            {'role': 'staff',
             'base_text': 'はい。最初にお試しいただくなら、こちらの方が普段使いしやすいかと存じます。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'はい。'},
                              {'intent': 'explanation', 'text': '最初にお試しいただくなら、こちらの方が普段使いしやすいかと存じます。'}]}]},
 {'id': 'apparel_payment',
  'venue': 'apparel',
  'title': '手続き系: 会計',
  'turns': [{'role': 'customer', 'text': 'これをお願いします。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。こちら1点でよろしいでしょうか？',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'question', 'text': 'こちら1点でよろしいでしょうか？'}]},
            {'role': 'customer', 'text': 'はい。'},
            {'role': 'staff',
             'base_text': 'お会計は4,900円でございます。お支払い方法はいかがなさいますでしょうか？',
             'intent_parts': [{'intent': 'explanation', 'text': 'お会計は4,900円でございます。'},
                              {'intent': 'question', 'text': 'お支払い方法はいかがなさいますでしょうか？'}]},
            {'role': 'customer', 'text': 'カードでお願いします。'},
            {'role': 'staff',
             'base_text': 'かしこまりました。こちらに差し込みをお願いいたします。',
             'intent_parts': [{'intent': 'acceptance', 'text': 'かしこまりました。'},
                              {'intent': 'request', 'text': 'こちらに差し込みをお願いいたします。'}]}]},
 {'id': 'apparel_out_of_stock',
  'venue': 'apparel',
  'title': '謝罪・代替提案系: 欲しい色が在庫切れ',
  'turns': [{'role': 'customer', 'text': 'この服の黒ってありますか？'},
            {'role': 'staff',
             'base_text': '申し訳ございません。黒は現在、店頭在庫を切らしております。',
             'intent_parts': [{'intent': 'apology', 'text': '申し訳ございません。'},
                              {'intent': 'explanation', 'text': '黒は現在、店頭在庫を切らしております。'}]},
            {'role': 'customer', 'text': 'そうなんですね。'},
            {'role': 'staff',
             'base_text': '近い雰囲気でしたら、こちらのチャコールグレーがございます。黒より少し柔らかい印象で、合わせやすいお色です。',
             'intent_parts': [{'intent': 'apology', 'text': '近い雰囲気でしたら、こちらのチャコールグレーがございます。'},
                              {'intent': 'explanation', 'text': '黒より少し柔らかい印象で、合わせやすいお色です。'}]},
            {'role': 'customer', 'text': 'それも見てみたいです。'},
            {'role': 'staff',
             'base_text': 'ありがとうございます。今お持ちいたします。黒をご希望でしたら、他店舗の在庫もお調べできます。',
             'intent_parts': [{'intent': 'gratitude', 'text': 'ありがとうございます。'},
                              {'intent': 'acceptance', 'text': '今お持ちいたします。'},
                              {'intent': 'apology', 'text': '黒をご希望でしたら、他店舗の在庫もお調べできます。'}]}]}]
